#!/bin/bash

# ========================================
# Script para configurar Neon.tech Database
# ========================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🗄️  Neon.tech Database Setup${NC}"
echo "======================================"
echo ""

echo -e "${YELLOW}📋 Paso 1: Crear cuenta en Neon.tech${NC}"
echo ""
echo "  1. Ir a: https://neon.tech"
echo "  2. Sign up (gratis)"
echo "  3. Crear nuevo proyecto: 'emotioxv3'"
echo "  4. Seleccionar región: US East (Ohio) - us-east-2"
echo ""
echo -e "${GREEN}✓ PostgreSQL 15.x${NC}"
echo -e "${GREEN}✓ Gratis hasta 10GB${NC}"
echo -e "${GREEN}✓ Serverless (escala a 0)${NC}"
echo ""

read -p "¿Ya creaste el proyecto en Neon.tech? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo ""
    echo "Por favor crea el proyecto primero y vuelve a ejecutar este script."
    exit 1
fi

echo ""
echo -e "${YELLOW}📋 Paso 2: Obtener Connection String${NC}"
echo ""
echo "En Neon.tech Dashboard:"
echo "  1. Click en tu proyecto 'emotioxv3'"
echo "  2. Click en 'Connection Details'"
echo "  3. Copiar los siguientes valores:"
echo ""
echo "Ejemplo de connection string:"
echo -e "${BLUE}postgresql://user:password@ep-xxxx.us-east-2.aws.neon.tech/emotioxv3?sslmode=require${NC}"
echo ""

read -p "Pega tu connection string aquí: " CONNECTION_STRING

# Parse connection string
if [[ $CONNECTION_STRING =~ postgresql://([^:]+):([^@]+)@([^/]+)/([^\?]+) ]]; then
    DB_USER="${BASH_REMATCH[1]}"
    DB_PASSWORD="${BASH_REMATCH[2]}"
    DB_HOST="${BASH_REMATCH[3]}"
    DB_NAME="${BASH_REMATCH[4]}"
    
    echo ""
    echo -e "${GREEN}✓ Connection string parseado correctamente${NC}"
    echo "  Host: $DB_HOST"
    echo "  User: $DB_USER"
    echo "  Database: $DB_NAME"
else
    echo -e "${YELLOW}⚠️  No se pudo parsear la connection string${NC}"
    echo "Ingresa los valores manualmente:"
    read -p "DB_HOST: " DB_HOST
    read -p "DB_USER: " DB_USER
    read -s -p "DB_PASSWORD: " DB_PASSWORD
    echo ""
    read -p "DB_NAME: " DB_NAME
fi

echo ""
echo -e "${YELLOW}📋 Paso 3: Actualizar .env.production${NC}"

# Update .env.production
cat > .env.production << EOF
# 🚀 PRODUCTION ENVIRONMENT - AWS with Neon.tech
# Auto-generated by setup-neon-db.sh

# Database - Neon.tech (PostgreSQL Serverless)
DB_HOST=$DB_HOST
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_SSL=true

# JWT
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production

# AWS S3 Configuration
APP_AWS_REGION=us-east-1
S3_BUCKET_NAME=emotioxv3-media-041238861016

# CORS
CORS_ORIGIN=*

# API Stage
API_STAGE=dev

# Cognito
COGNITO_USER_POOL_ID=us-east-1_BVc7DMwZd
COGNITO_CLIENT_ID=3enuct41ton6u3achfe2qtu2ff
EOF

echo -e "${GREEN}✓ .env.production actualizado${NC}"

echo ""
echo -e "${YELLOW}📋 Paso 4: Ejecutar migraciones${NC}"

# Test connection
echo "Probando conexión..."
export PGPASSWORD=$DB_PASSWORD
if psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "SELECT version();" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Conexión exitosa${NC}"
else
    echo -e "${YELLOW}⚠️  No se pudo conectar. Verifica las credenciales.${NC}"
    exit 1
fi

echo ""
read -p "¿Ejecutar migraciones ahora? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Ejecutando migraciones..."
    
    # Ejecutar archivos SQL en orden
    for file in ../database/migrations/*.sql; do
        if [ -f "$file" ]; then
            echo "  → $(basename $file)"
            psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -f "$file" -q
        fi
    done
    
    echo -e "${GREEN}✓ Migraciones completadas${NC}"
fi

echo ""
echo -e "${GREEN}✅ Setup completado!${NC}"
echo ""
echo "Próximos pasos:"
echo "  1. Revisar .env.production"
echo "  2. Re-desplegar backend: bash deploy-aws.sh"
echo "  3. Verificar logs: serverless logs -f api -t"
echo ""
