/**
 * Preguntas por defecto para mostrar cuando no hay configuración disponible
 */

import type { FinalQuestionData } from '../CognitiveTaskResults';

/**
 * Preguntas de ejemplo por defecto cuando no hay configuración
 */
export const DEFAULT_COGNITIVE_QUESTIONS: FinalQuestionData[] = [
  {
    key: 'question-cognitive_short_text',
    questionId: 'cognitive_short_text',
    questionType: 'short_text',
    questionText: 'Pregunta breve',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'sentiment',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_long_text',
    questionId: 'cognitive_long_text',
    questionType: 'long_text',
    questionText: 'Crees que podría mejorar?',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'sentiment',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_single_choice',
    questionId: 'cognitive_single_choice',
    questionType: 'multiple_choice',
    questionText: 'Cual de estos colores prefieres?',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'choice',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_multiple_choice',
    questionId: 'cognitive_multiple_choice',
    questionType: 'multiple_choice',
    questionText: 'Cual de estas opciones prefieres?',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'choice',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_linear_scale',
    questionId: 'cognitive_linear_scale',
    questionType: 'rating',
    questionText: 'Califica a la marca',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'linear_scale',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_ranking',
    questionId: 'cognitive_ranking',
    questionType: 'ranking',
    questionText: 'Cual es tu mayor preferencia',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'ranking',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_navigation_flow',
    questionId: 'cognitive_navigation_flow',
    questionType: 'rating',
    questionText: 'Flujo de navegación',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'navigation_flow',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  },
  {
    key: 'question-cognitive_preference_test',
    questionId: 'cognitive_preference_test',
    questionType: 'preference_test',
    questionText: 'Cual de estas imagenes te parece mas adecuada?',
    required: false,
    conditionalityDisabled: false,
    hasNewData: false,
    viewType: 'preference',
    sentimentData: undefined,
    choiceData: undefined,
    rankingData: undefined,
    linearScaleData: undefined,
    ratingData: undefined,
    preferenceTestData: undefined,
    imageSelectionData: undefined,
    navigationFlowData: undefined,
    initialActiveTab: 'sentiment',
    themeImageSrc: ''
  }
];

