# -*- coding: utf-8 -*-
"""Heatmap_con_cuadrantes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HGgOQtj9N8gWkFM5xvXFsZyEW6LXnBZ
"""

# Paso 1: Instalar dependencias necesarias
!pip install transformers timm --quiet

# Paso 2: Importar librerías
import torch
from transformers import AutoFeatureExtractor, AutoModel
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import requests
import cv2

# Paso 3: Cargar imagen
image_path = "screen.jpeg"  # Asegúrate de que la imagen esté en el mismo directorio
img = Image.open(image_path).convert('RGB')
img_np = np.array(img)

# Paso 4: Cargar modelo y extractor de características
model_name = "facebook/dino-vitb16"
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
model.eval()

# Paso 5: Preprocesar imagen
inputs = feature_extractor(images=img, return_tensors="pt")

# Paso 6: Obtener saliency map
with torch.no_grad():
    outputs = model(**inputs)
    attention = outputs.last_hidden_state
    # Calcular la atención promedio
    saliency_map = attention.mean(dim=1).squeeze().numpy()

# Paso 7: Normalizar y redimensionar saliency map
saliency_map -= saliency_map.min()
saliency_map /= saliency_map.max()
saliency_map = cv2.resize(saliency_map, (img_np.shape[1], img_np.shape[0]))

# Paso 8: Superponer saliency map sobre la imagen original
heatmap = cv2.applyColorMap(np.uint8(255 * saliency_map), cv2.COLORMAP_JET)
superimposed = cv2.addWeighted(heatmap, 0.6, img_np, 0.4, 0)

# Paso 9: Mostrar resultados
plt.figure(figsize=(14, 5))

plt.subplot(1, 3, 1)
plt.title("Imagen Original")
plt.imshow(img_np)
plt.axis("off")

plt.subplot(1, 3, 2)
plt.title("Mapa de Atención")
plt.imshow(saliency_map, cmap='jet')
plt.axis("off")

plt.subplot(1, 3, 3)
plt.title("Superposición")
plt.imshow(cv2.cvtColor(superimposed, cv2.COLOR_BGR2RGB))
plt.axis("off")

plt.tight_layout()
plt.show()

from google.colab import files
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

!pip install -q timm opencv-python

import torch
import torch.nn as nn
import torch.nn.functional as F
import timm
from torchvision import transforms
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import urllib.request

# Descargar pesos de modelo alternativo si no están
model_url = "https://github.com/matttaggart/DeepGazeII/releases/download/v0.0.1/deepgaze2.pth"
model_path = "deepgaze2.pth"
urllib.request.urlretrieve(model_url, model_path)

# Definir modelo DeepGaze II
class DeepGazeII(nn.Module):
    def __init__(self):
        super(DeepGazeII, self).__init__()
        self.backbone = timm.create_model('vgg19_bn', pretrained=True, features_only=True)
        self.readout = nn.Conv2d(512, 1, kernel_size=1)

    def forward(self, x):
        features = self.backbone(x)[-1]
        saliency = self.readout(features)
        saliency = F.relu(saliency)
        saliency = F.interpolate(saliency, size=x.shape[2:], mode='bilinear', align_corners=False)
        return saliency

# Cargar modelo
model = DeepGazeII()
model.load_state_dict(torch.load(model_path, map_location='cpu'))
model.eval()

# Cargar y procesar la imagen
img = Image.open(image_path).convert("RGB")
original_size = img.size

preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])
img_tensor = preprocess(img).unsqueeze(0)

# Ejecutar el modelo
with torch.no_grad():
    output = model(img_tensor)
    heatmap = output.squeeze().numpy()

# Normalizar y escalar al tamaño original
heatmap -= heatmap.min()
heatmap /= heatmap.max()
heatmap_resized = cv2.resize(heatmap, original_size[::-1])

# Convertir a formato OpenCV
img_np = np.array(img.resize(original_size))
img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)

# Crear heatmap y combinar
colored_heatmap = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
combined = cv2.addWeighted(colored_heatmap, 0.5, img_np, 0.5, 0)

# Mostrar
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(img)
plt.title("Imagen original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(heatmap_resized, cmap='jet')
plt.title("Mapa de atención")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(combined, cv2.COLOR_BGR2RGB))
plt.title("Superposición tipo Attention Insight")
plt.axis("off")
plt.show()

import cv2
import torch
import numpy as np
from transformers import AutoFeatureExtractor, AutoModel
from PIL import Image

# Cargar modelo y extractor de características
model_name = "facebook/dino-vitb16"
feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
model.eval()

# Ruta del video de entrada
video_path = "video.mp4"  # Asegúrate de que esté en el mismo directorio o usa ruta completa
cap = cv2.VideoCapture(video_path)

# Obtener propiedades del video original
fps = cap.get(cv2.CAP_PROP_FPS)
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Configurar VideoWriter para guardar el video de salida
out = cv2.VideoWriter(
    'output_saliency.mp4',
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (frame_width, frame_height)
)

frame_count = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convertir frame a imagen PIL (RGB)
    img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    img_np = np.array(img)

    # Preprocesar imagen
    inputs = feature_extractor(images=img, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)
        attention = outputs.last_hidden_state
        saliency_map = attention.mean(dim=1).squeeze().numpy()

    # Normalizar y redimensionar saliency map
    saliency_map -= saliency_map.min()
    saliency_map /= saliency_map.max()
    saliency_map = cv2.resize(saliency_map, (img_np.shape[1], img_np.shape[0]))

    # Superponer saliency map sobre frame original
    heatmap = cv2.applyColorMap(np.uint8(255 * saliency_map), cv2.COLORMAP_JET)
    superimposed = cv2.addWeighted(heatmap, 0.6, frame, 0.4, 0)

    # Escribir frame procesado al video de salida
    out.write(superimposed)

    frame_count += 1
    print(f"Procesado frame {frame_count}", end="\r")

# Liberar recursos
cap.release()
out.release()
print("\n✅ Video procesado guardado como 'output_saliency.mp4'")

import cv2
import torch
import numpy as np
from transformers import AutoFeatureExtractor, AutoModel
from PIL import Image
import os

def check_video_exists(video_path):
    """Verificar que el video existe"""
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"El archivo de video no existe: {video_path}")
    return True

def get_attention_map(model, feature_extractor, image):
    """Extraer mapa de atención del modelo DINO"""
    # Preprocesar imagen
    inputs = feature_extractor(images=image, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

        # Para DINO, usar el token [CLS] o promediar todos los tokens
        # Obtener las características del último layer
        last_hidden_states = outputs.last_hidden_state  # [batch, seq_len, hidden_dim]

        # DINO usa patches, necesitamos reshapear para obtener el mapa espacial
        # El primer token es [CLS], el resto son patches
        patch_tokens = last_hidden_states[0, 1:]  # Excluir [CLS] token

        # Calcular la atención promediando las dimensiones de características
        attention_map = torch.mean(patch_tokens, dim=-1)  # Promediar características

        # Determinar el tamaño de la grilla de patches
        num_patches = attention_map.shape[0]
        grid_size = int(np.sqrt(num_patches))

        # Verificar que es una grilla cuadrada válida
        if grid_size * grid_size != num_patches:
            # Si no es cuadrada, usar interpolación
            grid_size = int(np.sqrt(num_patches))
            attention_map = attention_map[:grid_size*grid_size]

        # Reshapear a mapa 2D
        attention_map = attention_map.reshape(grid_size, grid_size)

    return attention_map.numpy()

def create_saliency_heatmap(attention_map, target_size):
    """Crear heatmap a partir del mapa de atención"""
    # Normalizar el mapa de atención
    attention_map = (attention_map - attention_map.min()) / (attention_map.max() - attention_map.min())

    # Redimensionar al tamaño objetivo
    attention_resized = cv2.resize(attention_map, target_size, interpolation=cv2.INTER_CUBIC)

    # Crear heatmap con colormap
    heatmap = cv2.applyColorMap(np.uint8(255 * attention_resized), cv2.COLORMAP_JET)

    return heatmap, attention_resized

def main():
    # Cargar modelo y extractor de características
    print("🔄 Cargando modelo DINO...")
    model_name = "facebook/dino-vitb16"
    try:
        feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
        model = AutoModel.from_pretrained(model_name)
        model.eval()
        print("✅ Modelo cargado exitosamente")
    except Exception as e:
        print(f"❌ Error cargando modelo: {e}")
        return

    # Ruta del video de entrada
    video_path = "video.mp4"

    # Verificar que el video existe
    try:
        check_video_exists(video_path)
        print(f"✅ Video encontrado: {video_path}")
    except FileNotFoundError as e:
        print(f"❌ {e}")
        return

    # Abrir video
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Error: No se pudo abrir el video")
        return

    # Obtener propiedades del video original
    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    print(f"📹 Propiedades del video:")
    print(f"   - Resolución: {frame_width}x{frame_height}")
    print(f"   - FPS: {fps}")
    print(f"   - Total frames: {total_frames}")

    # Ajuste por rotación si es necesario
    rotate_frame = True  # Cambia a False si no necesitas rotar

    # Ajustar dimensiones si hay rotación
    if rotate_frame:
        output_frame_width = frame_height
        output_frame_height = frame_width
    else:
        output_frame_width = frame_width
        output_frame_height = frame_height

    # Nueva resolución para el video de salida: doble de ancho para poner lado a lado
    output_width = output_frame_width * 2
    output_height = output_frame_height

    print(f"📤 Video de salida: {output_width}x{output_height}")

    # Configurar VideoWriter para guardar el video de salida
    output_path = 'output_saliency_with_heatmap.mp4'
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (output_width, output_height))

    if not out.isOpened():
        print("❌ Error: No se pudo crear el archivo de video de salida")
        cap.release()
        return

    frame_count = 0
    processed_count = 0

    print("🔄 Procesando frames...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        try:
            # Rotar si es necesario
            if rotate_frame:
                frame = cv2.rotate(frame, cv2.ROTATE_90_COUNTERCLOCKWISE)

            # Convertir frame a imagen PIL (RGB)
            img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img_pil = Image.fromarray(img_rgb)

            # Obtener mapa de atención
            attention_map = get_attention_map(model, feature_extractor, img_pil)

            # Crear heatmap
            target_size = (frame.shape[1], frame.shape[0])  # (width, height)
            heatmap, attention_resized = create_saliency_heatmap(attention_map, target_size)

            # Superponer heatmap con frame original
            superimposed = cv2.addWeighted(frame, 0.4, heatmap, 0.6, 0)

            # Combinar original + heatmap en un solo frame lado a lado
            combined = np.hstack((frame, superimposed))

            # Verificar que las dimensiones coincidan
            if combined.shape[:2] != (output_height, output_width):
                combined = cv2.resize(combined, (output_width, output_height))

            # Escribir frame al video de salida
            out.write(combined)
            processed_count += 1

        except Exception as e:
            print(f"\n⚠️  Error procesando frame {frame_count}: {e}")
            continue

        frame_count += 1

        # Mostrar progreso cada 30 frames
        if frame_count % 30 == 0:
            progress = (frame_count / total_frames) * 100 if total_frames > 0 else 0
            print(f"Progreso: {frame_count}/{total_frames} frames ({progress:.1f}%) - Procesados: {processed_count}")

    # Liberar recursos
    cap.release()
    out.release()
    cv2.destroyAllWindows()

    if processed_count > 0:
        print(f"\n✅ Video procesado exitosamente!")
        print(f"   - Frames procesados: {processed_count}/{frame_count}")
        print(f"   - Archivo guardado: {output_path}")

        # Verificar el tamaño del archivo de salida
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path) / (1024 * 1024)  # MB
            print(f"   - Tamaño del archivo: {file_size:.2f} MB")
        else:
            print("⚠️  El archivo de salida no fue creado correctamente")
    else:
        print("❌ No se procesó ningún frame correctamente")

if __name__ == "__main__":
    main()

import cv2
import torch
import numpy as np
from transformers import AutoFeatureExtractor, AutoModel
from PIL import Image
import os

def check_video_exists(video_path):
    """Verificar que el video existe"""
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"El archivo de video no existe: {video_path}")
    return True

def get_attention_map(model, feature_extractor, image):
    """Extraer mapa de atención del modelo DINO"""
    # Preprocesar imagen
    inputs = feature_extractor(images=image, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

        # Para DINO, usar el token [CLS] o promediar todos los tokens
        # Obtener las características del último layer
        last_hidden_states = outputs.last_hidden_state  # [batch, seq_len, hidden_dim]

        # DINO usa patches, necesitamos reshapear para obtener el mapa espacial
        # El primer token es [CLS], el resto son patches
        patch_tokens = last_hidden_states[0, 1:]  # Excluir [CLS] token

        # Calcular la atención promediando las dimensiones de características
        attention_map = torch.mean(patch_tokens, dim=-1)  # Promediar características

        # Determinar el tamaño de la grilla de patches
        num_patches = attention_map.shape[0]
        grid_size = int(np.sqrt(num_patches))

        # Verificar que es una grilla cuadrada válida
        if grid_size * grid_size != num_patches:
            # Si no es cuadrada, usar interpolación
            grid_size = int(np.sqrt(num_patches))
            attention_map = attention_map[:grid_size*grid_size]

        # Reshapear a mapa 2D
        attention_map = attention_map.reshape(grid_size, grid_size)

    return attention_map.numpy()

def create_saliency_heatmap(attention_map, target_size):
    """Crear heatmap a partir del mapa de atención"""
    # Normalizar el mapa de atención
    attention_map = (attention_map - attention_map.min()) / (attention_map.max() - attention_map.min())

    # Redimensionar al tamaño objetivo
    attention_resized = cv2.resize(attention_map, target_size, interpolation=cv2.INTER_CUBIC)

    # Crear heatmap con colormap
    heatmap = cv2.applyColorMap(np.uint8(255 * attention_resized), cv2.COLORMAP_JET)

    return heatmap, attention_resized

def main():
    # Cargar modelo y extractor de características
    print("🔄 Cargando modelo DINO...")
    model_name = "facebook/dino-vitb16"
    try:
        feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
        model = AutoModel.from_pretrained(model_name)
        model.eval()
        print("✅ Modelo cargado exitosamente")
    except Exception as e:
        print(f"❌ Error cargando modelo: {e}")
        return

    # Ruta del video de entrada
    video_path = "video.mp4"

    # Verificar que el video existe
    try:
        check_video_exists(video_path)
        print(f"✅ Video encontrado: {video_path}")
    except FileNotFoundError as e:
        print(f"❌ {e}")
        return

    # Abrir video
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Error: No se pudo abrir el video")
        return

    # Obtener propiedades del video original
    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    print(f"📹 Propiedades del video:")
    print(f"   - Resolución: {frame_width}x{frame_height}")
    print(f"   - FPS: {fps}")
    print(f"   - Total frames: {total_frames}")

    # Ajuste por rotación si es necesario
    rotate_frame = True  # Cambia a False si no necesitas rotar

    # Ajustar dimensiones si hay rotación
    if rotate_frame:
        output_frame_width = frame_height
        output_frame_height = frame_width
    else:
        output_frame_width = frame_width
        output_frame_height = frame_height

    # Nueva resolución para el video de salida: doble de ancho para poner lado a lado
    output_width = output_frame_width * 2
    output_height = output_frame_height

    print(f"📤 Video de salida: {output_width}x{output_height}")

    # Configurar VideoWriter para guardar el video de salida
    output_path = 'output_saliency_with_heatmap.mp4'
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (output_width, output_height))

    if not out.isOpened():
        print("❌ Error: No se pudo crear el archivo de video de salida")
        cap.release()
        return

    frame_count = 0
    processed_count = 0

    print("🔄 Procesando frames...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        try:
            # Rotar si es necesario
            if rotate_frame:
                frame = cv2.rotate(frame, cv2.ROTATE_90_COUNTERCLOCKWISE)

            # Convertir frame a imagen PIL (RGB)
            img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img_pil = Image.fromarray(img_rgb)

            # Obtener mapa de atención
            attention_map = get_attention_map(model, feature_extractor, img_pil)

            # Crear heatmap
            target_size = (frame.shape[1], frame.shape[0])  # (width, height)
            heatmap, attention_resized = create_saliency_heatmap(attention_map, target_size)

            # Voltear el heatmap verticalmente para que coincida con la orientación del frame
            heatmap = cv2.flip(heatmap, 0)  # Flip vertical

            # Superponer heatmap con frame original
            superimposed = cv2.addWeighted(frame, 0.4, heatmap, 0.6, 0)

            # Combinar original + heatmap en un solo frame lado a lado
            combined = np.hstack((frame, superimposed))

            # Verificar que las dimensiones coincidan
            if combined.shape[:2] != (output_height, output_width):
                combined = cv2.resize(combined, (output_width, output_height))

            # Escribir frame al video de salida
            out.write(combined)
            processed_count += 1

        except Exception as e:
            print(f"\n⚠️  Error procesando frame {frame_count}: {e}")
            continue

        frame_count += 1

        # Mostrar progreso cada 30 frames
        if frame_count % 30 == 0:
            progress = (frame_count / total_frames) * 100 if total_frames > 0 else 0
            print(f"Progreso: {frame_count}/{total_frames} frames ({progress:.1f}%) - Procesados: {processed_count}")

    # Liberar recursos
    cap.release()
    out.release()
    cv2.destroyAllWindows()

    if processed_count > 0:
        print(f"\n✅ Video procesado exitosamente!")
        print(f"   - Frames procesados: {processed_count}/{frame_count}")
        print(f"   - Archivo guardado: {output_path}")

        # Verificar el tamaño del archivo de salida
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path) / (1024 * 1024)  # MB
            print(f"   - Tamaño del archivo: {file_size:.2f} MB")
        else:
            print("⚠️  El archivo de salida no fue creado correctamente")
    else:
        print("❌ No se procesó ningún frame correctamente")

if __name__ == "__main__":
    main()

import cv2
import torch
import numpy as np
from transformers import AutoFeatureExtractor, AutoModel
from PIL import Image
import os

def check_video_exists(video_path):
    """Verificar que el video existe"""
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"El archivo de video no existe: {video_path}")
    return True

def get_attention_map(model, feature_extractor, image):
    """Extraer mapa de atención del modelo DINO"""
    # Preprocesar imagen
    inputs = feature_extractor(images=image, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

        # Para DINO, usar el token [CLS] o promediar todos los tokens
        # Obtener las características del último layer
        last_hidden_states = outputs.last_hidden_state  # [batch, seq_len, hidden_dim]

        # DINO usa patches, necesitamos reshapear para obtener el mapa espacial
        # El primer token es [CLS], el resto son patches
        patch_tokens = last_hidden_states[0, 1:]  # Excluir [CLS] token

        # Calcular la atención promediando las dimensiones de características
        attention_map = torch.mean(patch_tokens, dim=-1)  # Promediar características

        # Determinar el tamaño de la grilla de patches
        num_patches = attention_map.shape[0]
        grid_size = int(np.sqrt(num_patches))

        # Verificar que es una grilla cuadrada válida
        if grid_size * grid_size != num_patches:
            # Si no es cuadrada, usar interpolación
            grid_size = int(np.sqrt(num_patches))
            attention_map = attention_map[:grid_size*grid_size]

        # Reshapear a mapa 2D
        attention_map = attention_map.reshape(grid_size, grid_size)

    return attention_map.numpy()

def create_saliency_heatmap(attention_map, target_size):
    """Crear heatmap a partir del mapa de atención"""
    # Normalizar el mapa de atención
    attention_map = (attention_map - attention_map.min()) / (attention_map.max() - attention_map.min())

    # Redimensionar al tamaño objetivo
    attention_resized = cv2.resize(attention_map, target_size, interpolation=cv2.INTER_CUBIC)

    # Crear heatmap con colormap
    heatmap = cv2.applyColorMap(np.uint8(255 * attention_resized), cv2.COLORMAP_JET)

    return heatmap, attention_resized

def calculate_quadrant_attention(attention_map):
    """Calcular el porcentaje de atención en cada cuadrante (3x3 grid)"""
    h, w = attention_map.shape

    # Dividir en 3x3 cuadrantes
    quadrant_h = h // 3
    quadrant_w = w // 3

    quadrants = {}
    total_attention = np.sum(attention_map)

    # Crear etiquetas para los cuadrantes (1-9)
    labels = [
        ['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']
    ]

    for i in range(3):
        for j in range(3):
            # Calcular límites del cuadrante
            start_h = i * quadrant_h
            end_h = (i + 1) * quadrant_h if i < 2 else h
            start_w = j * quadrant_w
            end_w = (j + 1) * quadrant_w if j < 2 else w

            # Extraer región del cuadrante
            quadrant_region = attention_map[start_h:end_h, start_w:end_w]
            quadrant_attention = np.sum(quadrant_region)

            # Calcular porcentaje
            percentage = (quadrant_attention / total_attention) * 100 if total_attention > 0 else 0

            quadrants[labels[i][j]] = {
                'percentage': percentage,
                'bounds': (start_w, start_h, end_w, end_h)
            }

    return quadrants

def create_heatmap_with_quadrants(frame, heatmap, quadrants):
    """Combinar heatmap con cuadrantes y porcentajes en un solo panel"""
    # Superponer heatmap con frame original
    superimposed = cv2.addWeighted(frame, 0.4, heatmap, 0.6, 0)

    h, w = superimposed.shape[:2]

    # Colores para las líneas y texto
    line_color = (255, 255, 255)  # Blanco
    text_color = (0, 255, 0)      # Verde
    bg_color = (0, 0, 0)          # Negro para fondo del texto

    # Dibujar líneas de división (3x3 grid)
    quadrant_h = h // 3
    quadrant_w = w // 3

    # Líneas horizontales
    for i in range(1, 3):
        y = i * quadrant_h
        cv2.line(superimposed, (0, y), (w, y), line_color, 2)

    # Líneas verticales
    for j in range(1, 3):
        x = j * quadrant_w
        cv2.line(superimposed, (x, 0), (x, h), line_color, 2)

    # Dibujar porcentajes en cada cuadrante
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.8
    thickness = 2

    for quadrant_id, data in quadrants.items():
        percentage = data['percentage']
        bounds = data['bounds']

        # Calcular posición del texto (abajo y centro del cuadrante)
        center_x = (bounds[0] + bounds[2]) // 2
        bottom_y = bounds[3] - 10  # 10 píxeles desde el borde inferior

        # Texto a mostrar
        text = f"Q{quadrant_id}: {percentage:.1f}%"

        # Calcular tamaño del texto para el fondo
        (text_w, text_h), baseline = cv2.getTextSize(text, font, font_scale, thickness)

        # Dibujar fondo negro para el texto
        bg_x1 = center_x - text_w // 2 - 5
        bg_y1 = bottom_y - text_h - 5
        bg_x2 = center_x + text_w // 2 + 5
        bg_y2 = bottom_y + 5

        cv2.rectangle(superimposed, (bg_x1, bg_y1), (bg_x2, bg_y2), bg_color, -1)

        # Dibujar el texto
        text_x = center_x - text_w // 2
        text_y = bottom_y
        cv2.putText(superimposed, text, (text_x, text_y), font, font_scale, text_color, thickness)

    return superimposed

def main():
    # Cargar modelo y extractor de características
    print("🔄 Cargando modelo DINO...")
    model_name = "facebook/dino-vitb16"
    try:
        feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
        model = AutoModel.from_pretrained(model_name)
        model.eval()
        print("✅ Modelo cargado exitosamente")
    except Exception as e:
        print(f"❌ Error cargando modelo: {e}")
        return

    # Ruta del video de entrada
    video_path = "video.mp4"

    # Verificar que el video existe
    try:
        check_video_exists(video_path)
        print(f"✅ Video encontrado: {video_path}")
    except FileNotFoundError as e:
        print(f"❌ {e}")
        return

    # Abrir video
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Error: No se pudo abrir el video")
        return

    # Obtener propiedades del video original
    fps = cap.get(cv2.CAP_PROP_FPS)
    original_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    original_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # Intercambiar dimensiones después de la rotación
    frame_width = original_height  # Después de rotar 90°
    frame_height = original_width  # Después de rotar 90°

    print(f"📹 Propiedades del video:")
    print(f"   - Resolución original: {original_width}x{original_height}")
    print(f"   - Resolución después de rotación: {frame_width}x{frame_height}")
    print(f"   - FPS: {fps}")
    print(f"   - Total frames: {total_frames}")

    # Usar dimensiones después de la rotación
    output_frame_width = frame_width
    output_frame_height = frame_height

    # Nueva resolución para el video de salida: dos columnas (original + heatmap con cuadrantes)
    output_width = output_frame_width * 2  # Solo 2 paneles
    output_height = output_frame_height

    print(f"📤 Video de salida: {output_width}x{output_height}")

    # Configurar VideoWriter para guardar el video de salida
    output_path = 'output_saliency_combined.mp4'
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (output_width, output_height))

    if not out.isOpened():
        print("❌ Error: No se pudo crear el archivo de video de salida")
        cap.release()
        return

    frame_count = 0
    processed_count = 0

    print("🔄 Procesando frames...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        try:
            # Rotar el frame 90 grados en sentido horario para orientación horizontal
            frame = cv2.rotate(frame, cv2.ROTATE_90_CLOCKWISE)

            # Convertir frame a imagen PIL (RGB)
            img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img_pil = Image.fromarray(img_rgb)

            # Obtener mapa de atención
            attention_map = get_attention_map(model, feature_extractor, img_pil)

            # Crear heatmap
            target_size = (frame.shape[1], frame.shape[0])  # (width, height)
            heatmap, attention_resized = create_saliency_heatmap(attention_map, target_size)

            # Voltear el heatmap verticalmente para que coincida con la orientación del frame
            heatmap = cv2.flip(heatmap, 0)  # Flip vertical
            attention_resized = np.flip(attention_resized, 0)  # Flip vertical también para el cálculo

            # Calcular porcentajes por cuadrante
            quadrants = calculate_quadrant_attention(attention_resized)

            # Crear panel combinado (heatmap + cuadrantes)
            combined_heatmap = create_heatmap_with_quadrants(frame, heatmap, quadrants)

            # Combinar original + heatmap con cuadrantes (2 paneles)
            combined = np.hstack((frame, combined_heatmap))

            # Verificar que las dimensiones coincidan
            if combined.shape[1] != output_width:
                combined = cv2.resize(combined, (output_width, output_height))

            # Escribir frame al video de salida
            out.write(combined)
            processed_count += 1

        except Exception as e:
            print(f"\n⚠️  Error procesando frame {frame_count}: {e}")
            continue

        frame_count += 1

        # Mostrar progreso cada 30 frames
        if frame_count % 30 == 0:
            progress = (frame_count / total_frames) * 100 if total_frames > 0 else 0
            print(f"Progreso: {frame_count}/{total_frames} frames ({progress:.1f}%) - Procesados: {processed_count}")

    # Liberar recursos
    cap.release()
    out.release()
    cv2.destroyAllWindows()

    if processed_count > 0:
        print(f"\n✅ Video procesado exitosamente!")
        print(f"   - Frames procesados: {processed_count}/{frame_count}")
        print(f"   - Archivo guardado: {output_path}")

        # Verificar el tamaño del archivo de salida
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path) / (1024 * 1024)  # MB
            print(f"   - Tamaño del archivo: {file_size:.2f} MB")
        else:
            print("⚠️  El archivo de salida no fue creado correctamente")
    else:
        print("❌ No se procesó ningún frame correctamente")

if __name__ == "__main__":
    main()

import cv2
import torch
import numpy as np
from transformers import AutoFeatureExtractor, AutoModel
from PIL import Image
import os

def check_video_exists(video_path):
    """Verificar que el video existe"""
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"El archivo de video no existe: {video_path}")
    return True

def load_logo(logo_path, max_height=80):
    """Cargar y redimensionar el logo"""
    print(f"🔍 Buscando logo en: {os.path.abspath(logo_path)}")

    if not os.path.exists(logo_path):
        print(f"❌ Logo no encontrado: {logo_path}")
        print(f"📁 Archivos en el directorio actual:")
        try:
            files = [f for f in os.listdir('.') if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff'))]
            for f in files:
                print(f"   - {f}")
        except:
            pass
        return None

    try:
        logo = cv2.imread(logo_path, cv2.IMREAD_UNCHANGED)
        if logo is None:
            print(f"❌ No se pudo cargar el logo: {logo_path}")
            return None

        print(f"✅ Logo cargado: {logo.shape} (height, width, channels)")

        # Si el logo tiene canal alpha, manejarlo
        if len(logo.shape) == 3 and logo.shape[2] == 4:
            print("🔍 Logo tiene canal alpha (transparencia)")
            # Separar canales BGR y alpha
            bgr = logo[:, :, :3]
            alpha = logo[:, :, 3]
            logo = bgr
            logo_alpha = alpha
        else:
            print("🔍 Logo sin canal alpha")
            logo_alpha = None

        # Redimensionar manteniendo aspecto si es muy alto
        height, width = logo.shape[:2]
        print(f"📏 Dimensiones originales: {width}x{height}")

        if height > max_height:
            scale = max_height / height
            new_width = int(width * scale)
            new_height = max_height
            logo = cv2.resize(logo, (new_width, new_height))
            if logo_alpha is not None:
                logo_alpha = cv2.resize(logo_alpha, (new_width, new_height))
            print(f"📏 Redimensionado a: {new_width}x{new_height}")

        return logo, logo_alpha
    except Exception as e:
        print(f"❌ Error cargando logo: {e}")
        return None

def create_footer_with_logo(width, height, logo_data):
    """Crear franja negra con logo centrado"""
    footer = np.zeros((height, width, 3), dtype=np.uint8)  # Fondo negro

    print(f"🔧 Creando footer: {width}x{height}")

    if logo_data is None:
        print("⚠️ No hay logo para mostrar en el footer")
        # Agregar texto indicativo para debug
        cv2.putText(footer, "NO LOGO", (width//2 - 50, height//2),
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
        return footer

    logo, logo_alpha = logo_data
    logo_height, logo_width = logo.shape[:2]

    print(f"📍 Posicionando logo: {logo_width}x{logo_height}")

    # Calcular posición para centrar el logo
    start_x = (width - logo_width) // 2
    start_y = (height - logo_height) // 2

    print(f"📍 Posición del logo: ({start_x}, {start_y})")

    # Asegurarse de que el logo cabe en la franja
    if start_x < 0 or start_y < 0 or start_x + logo_width > width or start_y + logo_height > height:
        print(f"❌ El logo es demasiado grande para la franja")
        print(f"   Footer: {width}x{height}, Logo: {logo_width}x{logo_height}")
        print(f"   Posición calculada: ({start_x}, {start_y})")
        # Mostrar texto de error
        cv2.putText(footer, "LOGO TOO BIG", (width//2 - 80, height//2),
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        return footer

    # Colocar el logo
    end_x = start_x + logo_width
    end_y = start_y + logo_height

    try:
        if logo_alpha is not None:
            print("🎨 Aplicando logo con transparencia")
            # Aplicar logo con transparencia
            alpha_norm = logo_alpha.astype(float) / 255.0
            alpha_norm = np.expand_dims(alpha_norm, axis=2)  # Convertir a 3D

            # Blend con canal alpha
            footer_section = footer[start_y:end_y, start_x:end_x].astype(float)
            logo_float = logo.astype(float)

            blended = footer_section * (1 - alpha_norm) + logo_float * alpha_norm
            footer[start_y:end_y, start_x:end_x] = blended.astype(np.uint8)
        else:
            print("🎨 Aplicando logo sin transparencia")
            # Colocar logo sin transparencia
            footer[start_y:end_y, start_x:end_x] = logo

        print("✅ Logo aplicado correctamente al footer")

    except Exception as e:
        print(f"❌ Error aplicando logo al footer: {e}")
        # Mostrar texto de error
        cv2.putText(footer, "LOGO ERROR", (width//2 - 70, height//2),
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2)

    return footer

def get_attention_map(model, feature_extractor, image):
    """Extraer mapa de atención del modelo DINO"""
    # Preprocesar imagen
    inputs = feature_extractor(images=image, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

        # Para DINO, usar el token [CLS] o promediar todos los tokens
        # Obtener las características del último layer
        last_hidden_states = outputs.last_hidden_state  # [batch, seq_len, hidden_dim]

        # DINO usa patches, necesitamos reshapear para obtener el mapa espacial
        # El primer token es [CLS], el resto son patches
        patch_tokens = last_hidden_states[0, 1:]  # Excluir [CLS] token

        # Calcular la atención promediando las dimensiones de características
        attention_map = torch.mean(patch_tokens, dim=-1)  # Promediar características

        # Determinar el tamaño de la grilla de patches
        num_patches = attention_map.shape[0]
        grid_size = int(np.sqrt(num_patches))

        # Verificar que es una grilla cuadrada válida
        if grid_size * grid_size != num_patches:
            # Si no es cuadrada, usar interpolación
            grid_size = int(np.sqrt(num_patches))
            attention_map = attention_map[:grid_size*grid_size]

        # Reshapear a mapa 2D
        attention_map = attention_map.reshape(grid_size, grid_size)

    return attention_map.numpy()

def create_saliency_heatmap(attention_map, target_size):
    """Crear heatmap a partir del mapa de atención"""
    # Normalizar el mapa de atención
    attention_map = (attention_map - attention_map.min()) / (attention_map.max() - attention_map.min())

    # Redimensionar al tamaño objetivo
    attention_resized = cv2.resize(attention_map, target_size, interpolation=cv2.INTER_CUBIC)

    # Crear heatmap con colormap
    heatmap = cv2.applyColorMap(np.uint8(255 * attention_resized), cv2.COLORMAP_JET)

    return heatmap, attention_resized

def calculate_quadrant_attention(attention_map):
    """Calcular el porcentaje de atención en cada cuadrante (3x3 grid)"""
    h, w = attention_map.shape

    # Dividir en 3x3 cuadrantes
    quadrant_h = h // 3
    quadrant_w = w // 3

    quadrants = {}
    total_attention = np.sum(attention_map)

    # Crear etiquetas para los cuadrantes (1-9)
    labels = [
        ['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']
    ]

    for i in range(3):
        for j in range(3):
            # Calcular límites del cuadrante
            start_h = i * quadrant_h
            end_h = (i + 1) * quadrant_h if i < 2 else h
            start_w = j * quadrant_w
            end_w = (j + 1) * quadrant_w if j < 2 else w

            # Extraer región del cuadrante
            quadrant_region = attention_map[start_h:end_h, start_w:end_w]
            quadrant_attention = np.sum(quadrant_region)

            # Calcular porcentaje
            percentage = (quadrant_attention / total_attention) * 100 if total_attention > 0 else 0

            quadrants[labels[i][j]] = {
                'percentage': percentage,
                'bounds': (start_w, start_h, end_w, end_h)
            }

    return quadrants

def create_heatmap_with_quadrants(frame, heatmap, quadrants):
    """Combinar heatmap con cuadrantes y porcentajes en un solo panel"""
    # Superponer heatmap con frame original
    superimposed = cv2.addWeighted(frame, 0.4, heatmap, 0.6, 0)

    h, w = superimposed.shape[:2]

    # Colores para las líneas y texto
    line_color = (255, 255, 255)  # Blanco
    text_color = (0, 255, 0)      # Verde
    bg_color = (0, 0, 0)          # Negro para fondo del texto

    # Dibujar líneas de división (3x3 grid)
    quadrant_h = h // 3
    quadrant_w = w // 3

    # Líneas horizontales
    for i in range(1, 3):
        y = i * quadrant_h
        cv2.line(superimposed, (0, y), (w, y), line_color, 2)

    # Líneas verticales
    for j in range(1, 3):
        x = j * quadrant_w
        cv2.line(superimposed, (x, 0), (x, h), line_color, 2)

    # Dibujar porcentajes en cada cuadrante
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.8
    thickness = 2

    for quadrant_id, data in quadrants.items():
        percentage = data['percentage']
        bounds = data['bounds']

        # Calcular posición del texto (abajo y centro del cuadrante)
        center_x = (bounds[0] + bounds[2]) // 2
        bottom_y = bounds[3] - 10  # 10 píxeles desde el borde inferior

        # Texto a mostrar
        text = f"Q{quadrant_id}: {percentage:.1f}%"

        # Calcular tamaño del texto para el fondo
        (text_w, text_h), baseline = cv2.getTextSize(text, font, font_scale, thickness)

        # Dibujar fondo negro para el texto
        bg_x1 = center_x - text_w // 2 - 5
        bg_y1 = bottom_y - text_h - 5
        bg_x2 = center_x + text_w // 2 + 5
        bg_y2 = bottom_y + 5

        cv2.rectangle(superimposed, (bg_x1, bg_y1), (bg_x2, bg_y2), bg_color, -1)

        # Dibujar el texto
        text_x = center_x - text_w // 2
        text_y = bottom_y
        cv2.putText(superimposed, text, (text_x, text_y), font, font_scale, text_color, thickness)

    return superimposed

def main():
    # Configuración del logo
    logo_path = "logo.png"  # Cambia esto por la ruta de tu logo
    footer_height = 100     # Altura de la franja negra en píxeles

    # Intentar diferentes nombres de archivo comunes para el logo
    possible_logo_names = [
        "logo.png", "logo.jpg", "logo.jpeg",
        "Logo.png", "Logo.jpg", "Logo.jpeg",
        "LOGO.PNG", "LOGO.JPG", "LOGO.JPEG"
    ]

    logo_data = None
    # Cargar logo
    print("🔄 Cargando logo...")

    for logo_name in possible_logo_names:
        if os.path.exists(logo_name):
            logo_path = logo_name
            break

    logo_data = load_logo(logo_path, max_height=footer_height - 20)  # Dejar margen
    if logo_data:
        print("✅ Logo cargado exitosamente")
    else:
        print("⚠️ Continuando sin logo - se mostrará texto indicativo")

    # Cargar modelo y extractor de características
    print("🔄 Cargando modelo DINO...")
    model_name = "facebook/dino-vitb16"
    try:
        feature_extractor = AutoFeatureExtractor.from_pretrained(model_name)
        model = AutoModel.from_pretrained(model_name)
        model.eval()
        print("✅ Modelo cargado exitosamente")
    except Exception as e:
        print(f"❌ Error cargando modelo: {e}")
        return

    # Ruta del video de entrada
    video_path = "video.mp4"

    # Verificar que el video existe
    try:
        check_video_exists(video_path)
        print(f"✅ Video encontrado: {video_path}")
    except FileNotFoundError as e:
        print(f"❌ {e}")
        return

    # Abrir video
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Error: No se pudo abrir el video")
        return

    # Obtener propiedades del video original
    fps = cap.get(cv2.CAP_PROP_FPS)
    original_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    original_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # Intercambiar dimensiones después de la rotación
    frame_width = original_height  # Después de rotar 90°
    frame_height = original_width  # Después de rotar 90°

    print(f"📹 Propiedades del video:")
    print(f"   - Resolución original: {original_width}x{original_height}")
    print(f"   - Resolución después de rotación: {frame_width}x{frame_height}")
    print(f"   - FPS: {fps}")
    print(f"   - Total frames: {total_frames}")

    # Usar dimensiones después de la rotación
    output_frame_width = frame_width
    output_frame_height = frame_height

    # Nueva resolución para el video de salida: dos columnas + franja inferior
    content_width = output_frame_width * 2  # Dos paneles
    content_height = output_frame_height

    # Dimensiones finales incluyendo la franja del logo
    final_width = content_width
    final_height = content_height + footer_height

    print(f"📤 Video de salida: {final_width}x{final_height} (contenido: {content_width}x{content_height} + footer: {footer_height}px)")

    # Configurar VideoWriter para guardar el video de salida
    output_path = 'output_saliency_with_logo.mp4'
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (final_width, final_height))

    if not out.isOpened():
        print("❌ Error: No se pudo crear el archivo de video de salida")
        cap.release()
        return

    # Crear franja del footer una sola vez (es estática)
    footer = create_footer_with_logo(final_width, footer_height, logo_data)

    frame_count = 0
    processed_count = 0

    print("🔄 Procesando frames...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        try:
            # Rotar el frame 90 grados en sentido horario para orientación horizontal
            frame = cv2.rotate(frame, cv2.ROTATE_90_CLOCKWISE)

            # Convertir frame a imagen PIL (RGB)
            img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img_pil = Image.fromarray(img_rgb)

            # Obtener mapa de atención
            attention_map = get_attention_map(model, feature_extractor, img_pil)

            # Crear heatmap
            target_size = (frame.shape[1], frame.shape[0])  # (width, height)
            heatmap, attention_resized = create_saliency_heatmap(attention_map, target_size)

            # Voltear el heatmap verticalmente para que coincida con la orientación del frame
            heatmap = cv2.flip(heatmap, 0)  # Flip vertical
            attention_resized = np.flip(attention_resized, 0)  # Flip vertical también para el cálculo

            # Calcular porcentajes por cuadrante
            quadrants = calculate_quadrant_attention(attention_resized)

            # Crear panel combinado (heatmap + cuadrantes)
            combined_heatmap = create_heatmap_with_quadrants(frame, heatmap, quadrants)

            # Combinar original + heatmap con cuadrantes (2 paneles)
            content = np.hstack((frame, combined_heatmap))

            # Verificar que las dimensiones del contenido coincidan
            if content.shape[1] != content_width or content.shape[0] != content_height:
                content = cv2.resize(content, (content_width, content_height))

            # Combinar contenido + footer
            final_frame = np.vstack((content, footer))

            # Escribir frame al video de salida
            out.write(final_frame)
            processed_count += 1

        except Exception as e:
            print(f"\n⚠️  Error procesando frame {frame_count}: {e}")
            continue

        frame_count += 1

        # Mostrar progreso cada 30 frames
        if frame_count % 30 == 0:
            progress = (frame_count / total_frames) * 100 if total_frames > 0 else 0
            print(f"Progreso: {frame_count}/{total_frames} frames ({progress:.1f}%) - Procesados: {processed_count}")

    # Liberar recursos
    cap.release()
    out.release()
    cv2.destroyAllWindows()

    if processed_count > 0:
        print(f"\n✅ Video procesado exitosamente!")
        print(f"   - Frames procesados: {processed_count}/{frame_count}")
        print(f"   - Archivo guardado: {output_path}")

        # Verificar el tamaño del archivo de salida
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path) / (1024 * 1024)  # MB
            print(f"   - Tamaño del archivo: {file_size:.2f} MB")
        else:
            print("⚠️  El archivo de salida no fue creado correctamente")
    else:
        print("❌ No se procesó ningún frame correctamente")

if __name__ == "__main__":
    main()